//package com.didi.virtualapk.demo.database.greendao;
//
//import android.database.Cursor;
//import android.database.sqlite.SQLiteStatement;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.Property;
//import org.greenrobot.greendao.internal.DaoConfig;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.database.DatabaseStatement;
//
//import com.didi.virtualapk.demo.database.ConfigData;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
///**
// * DAO for table "CONFIG_DATA".
//*/
//public class ConfigDataDao extends AbstractDao<ConfigData, Long> {
//
//    public static final String TABLENAME = "CONFIG_DATA";
//
//    /**
//     * Properties of entity ConfigData.<br/>
//     * Can be used for QueryBuilder and for referencing column names.
//     */
//    public static class Properties {
//        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
//        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
//        public final static Property Json = new Property(2, String.class, "json", false, "JSON");
//    }
//
//
//    public ConfigDataDao(DaoConfig config) {
//        super(config);
//    }
//
//    public ConfigDataDao(DaoConfig config, DaoSession daoSession) {
//        super(config, daoSession);
//    }
//
//    /** Creates the underlying database table. */
//    public static void createTable(Database db, boolean ifNotExists) {
//        String constraint = ifNotExists? "IF NOT EXISTS ": "";
//        db.execSQL("CREATE TABLE " + constraint + "\"CONFIG_DATA\" (" + //
//                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
//                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
//                "\"JSON\" TEXT);"); // 2: json
//    }
//
//    /** Drops the underlying database table. */
//    public static void dropTable(Database db, boolean ifExists) {
//        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONFIG_DATA\"";
//        db.execSQL(sql);
//    }
//
//    @Override
//    protected final void bindValues(DatabaseStatement stmt, ConfigData entity) {
//        stmt.clearBindings();
//
//        Long id = entity.getId();
//        if (id != null) {
//            stmt.bindLong(1, id);
//        }
//        stmt.bindLong(2, entity.getType());
//
//        String json = entity.getJson();
//        if (json != null) {
//            stmt.bindString(3, json);
//        }
//    }
//
//    @Override
//    protected final void bindValues(SQLiteStatement stmt, ConfigData entity) {
//        stmt.clearBindings();
//
//        Long id = entity.getId();
//        if (id != null) {
//            stmt.bindLong(1, id);
//        }
//        stmt.bindLong(2, entity.getType());
//
//        String json = entity.getJson();
//        if (json != null) {
//            stmt.bindString(3, json);
//        }
//    }
//
//    @Override
//    public Long readKey(Cursor cursor, int offset) {
//        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
//    }
//
//    @Override
//    public ConfigData readEntity(Cursor cursor, int offset) {
//        ConfigData entity = new ConfigData( //
//            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
//            cursor.getInt(offset + 1), // type
//            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // json
//        );
//        return entity;
//    }
//
//    @Override
//    public void readEntity(Cursor cursor, ConfigData entity, int offset) {
//        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
//        entity.setType(cursor.getInt(offset + 1));
//        entity.setJson(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
//     }
//
//    @Override
//    protected final Long updateKeyAfterInsert(ConfigData entity, long rowId) {
//        entity.setId(rowId);
//        return rowId;
//    }
//
//    @Override
//    public Long getKey(ConfigData entity) {
//        if(entity != null) {
//            return entity.getId();
//        } else {
//            return null;
//        }
//    }
//
//    @Override
//    public boolean hasKey(ConfigData entity) {
//        return entity.getId() != null;
//    }
//
//    @Override
//    protected final boolean isEntityUpdateable() {
//        return true;
//    }
//
//}
