//package com.didi.virtualapk.demo.database.greendao;
//
//import java.util.Map;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.AbstractDaoSession;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.identityscope.IdentityScopeType;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//import com.didi.virtualapk.demo.database.ConfigData;
//
//import com.didi.virtualapk.demo.database.greendao.ConfigDataDao;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see org.greenrobot.greendao.AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig configDataDaoConfig;
//
//    private final ConfigDataDao configDataDao;
//
//    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        configDataDaoConfig = daoConfigMap.get(ConfigDataDao.class).clone();
//        configDataDaoConfig.initIdentityScope(type);
//
//        configDataDao = new ConfigDataDao(configDataDaoConfig, this);
//
//        registerDao(ConfigData.class, configDataDao);
//    }
//
//    public void clear() {
//        configDataDaoConfig.clearIdentityScope();
//    }
//
//    public ConfigDataDao getConfigDataDao() {
//        return configDataDao;
//    }
//
//}
